services:
  - type: web
    name: geo
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: waitress-serve --port=$PORT gee_backend.wsgi:application
    envVars:
      - key: DATABASE_URL
        value: your-database-url
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: false
